### ISSUE TITLE
A beginner in ROS

### ISSUE THREAD

**Issue by 245679383** [apgeorg/tiny_usb_cam#4]
Hi sir,

Could you please tell me how to install and run this package in ROS?

Best regards.

**Comment by apgeorg** [comment]
Hi, 
do you have a running ROS installation?
Best regards

**Comment by 245679383** [comment]
Yes.
I have installed one on Ubuntu and could open the usb camera by opencv on ROS.

**Comment by apgeorg** [comment]
Ok, just clone the repository in your catkin_ws/src folder like: `git clone https://github.com/apgeorg/tiny_usb_cam.git camera`  and than build with `catkin_make` and `source devel/setup.bash` as described in the ros tutorials. If its successfully built, you can try to run the launch file with:  
`roslaunch src/camera/launch/live_view.launch`

I will also provide in the future some installations instructions :)
Best

**Comment by 245679383** [comment]
Thank you very much☺️

**Comment by apgeorg** [comment]
Your welcome!

**Comment by apgeorg** [comment]
Does it work?
